### ISSUE TITLE
If the service takes a long time to start,admin checkd upstream fail,it can't be registed

### ISSUE THREAD

**Issue by 512222607** [dromara/soul#1127] opened 2021-02-26 02:27 UTC
## Environment

- Soul version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment] 2021-02-26 02:49
can you fix it？

**Comment by dengliming** [comment] 2021-02-26 03:45
Duplicate of [https://github.com/dromara/soul/issues/1113](https://github.com/dromara/soul/issues/1113)

**Closed by dengliming** 2021-02-26 03:45 UTC
Labels: type: bug
