### ISSUE TITLE
When the Dubbo interface has multiple parameters, must the client request bring in JSON in the same order as the interface parameters

### ISSUE THREAD

**Issue by tjling** [dromara/soul#1124] opened 2021-02-25 06:37 UTC
## Question

When the Dubbo interface has multiple parameters, must the client request bring in JSON in the same order as the interface parameters

**Comment by yu199195** [comment] 2021-02-25 07:08
pls  in english

**Comment by dengliming** [comment] 2021-02-26 03:43
Duplicate of [https://github.com/dromara/soul/issues/1026](https://github.com/dromara/soul/issues/1026)

**Closed by dengliming** 2021-02-26 03:43 UTC
Labels: type: duplicate, type: question
